version: '3.8'
services:
  nats:
    image: nats:2.9-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]
    volumes:
      - ./data/nats/jetstream:/data/jetstream
      - ./data/nats/config:/etc/nats
    environment:
      - JS_STORE_DIR=/data/jetstream
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI
      - "14250:14250"  # Model
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686" ]
      interval: 5s
      timeout: 3s
      retries: 3

  click-server:
    build:
      context: ./
      dockerfile: Dockerfile.click-server
    image: ghcr.io/valdo404/clickplanet-rust-state-click-server:latest
    environment:
      - RUST_LOG=debug
    command: [
      "--nats-url", "nats://nats:4222",
      "--redis-url", "redis://redis:6379",
      "--otlp-endpoint", "jaeger:4317",
      "--service-name", "click-server"
    ]
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
      jaeger:
        condition: service_started

  state-click-persister:
    build:
      context: ./
      dockerfile: Dockerfile.click-persister
    image: ghcr.io/valdo404/clickplanet-rust-state-click-persister:latest
    environment:
      - RUST_LOG=debug
    command: [
      "--nats-url", "nats://nats:4222",
      "--redis-url", "redis://redis:6379",
      "--otlp-endpoint", "jaeger:4317",
      "--service-name", "click-persister",
      "--concurrent-processors", "8",
      "--ack-wait-secs", "10"
    ]
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
      jaeger:
        condition: service_started

  tile-syncer:
    build:
      context: ./
      dockerfile: Dockerfile.tile-syncer-robot
    image: ghcr.io/valdo404/clickplanet-rust-tile-syncer:latest
    environment:
      - RUST_LOG=debug
    command: [
      "--prod-host", "clickplanet.lol",
      "--local-host", "click-server",  # Use the service name as host
      "--local-port", "3000",
      "--coordinates-file", "/app/coordinates.json"
    ]
    volumes:
      - ./coordinates.json:/app/coordinates.json:ro
    networks:
      - app-network
    depends_on:
      click-server:
        condition: service_started

networks:
  app-network:
    driver: bridge
